### PR TITLE
Added road names to stops.json and stops.geojson

### PR DESCRIPTION
**Pull request by nelss-xyz**

### CODE REVIEW

**Comment by cheeaun** [comment]
Hi thanks for the PR, sorry for this late response.

Question, are you using this data in some form or application? I'm asking because I'm wondering how people are utilising this road name data.

Few considerations:

- Some stops probably will be missing road names, so it's not *complete*.
- Adding road names will increase the file size.

**Comment by SlenPlayz** [comment]
Hi yea I'm using it in [@SlenPlayz/SGBus-web](https://github.com/SlenPlayz/SGBus-web) which is the server for my app. I might fork this repo and self host all my data but for the time being I'm using it for the app to get data even when offline and for the road names it makes it easier to search for stops

**Comment by SlenPlayz** [comment]
Hey just checked there doesnt seem to be any missing road names for any stops

**Comment by SlenPlayz** [comment]
Any updates?

**Comment by cheeaun** [comment]
Hey sorry for the late response, will merge.

**Pull request merged**
